/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-04-02 12:05:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import me.max.models.User;

public final class employee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("me.max.models.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

User user = (User) session.getAttribute("user");
String fName = user.getFirstName();
String lName = user.getLastName();
String email = user.getEmail();
int id = user.getId();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Home</title>\n");
      out.write("<link\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\"\n");
      out.write("\tintegrity=\"sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6\"\n");
      out.write("\tcrossorigin=\"anonymous\" />\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\">\n");
      out.write("</head>\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- Navbar! -->\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-light\">\n");
      out.write("\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#\">MERS</a>\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\"\n");
      out.write("\t\t\t\tdata-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\n");
      out.write("\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\"\n");
      out.write("\t\t\t\t\t\taria-current=\"page\" href=\"#\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><button class=\"nav-link btn\"\n");
      out.write("\t\t\t\t\t\t\ttype=\"button\" data-bs-toggle=\"modal\"\n");
      out.write("\t\t\t\t\t\t\tdata-bs-target=\"#requestModal\">New Request</button></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\thref=\"/ExpenseReimbursementSystem/logout\">Logout</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\t<main class=\"container\">\n");
      out.write("\t\t<!-- User Sidebar -->\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-3\" id=\"userInfo\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<h5>\n");
      out.write("\t\t\t\t\t\t");

						out.print(fName + " " + lName);
						
      out.write("\n");
      out.write("\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t");

						out.print("Employee ID: " + "<span id=uId>" + id + "</span>");
						
      out.write("\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t");

						out.print("Email: " + email);
						
      out.write("\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<p id=\"editPrompt\" data-bs-toggle=\"modal\"\n");
      out.write("\t\t\t\t\t\tdata-bs-target=\"#updateModal\">\n");
      out.write("\t\t\t\t\t\tEdit profile <i class=\"bi bi-pencil\"></i>\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- Main Request navigation/display -->\n");
      out.write("\t\t\t<div class=\"col-9\">\n");
      out.write("\t\t\t\t<ul class=\"nav nav-tabs\" role=\"tablist\">\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\" id=\"pendingTab\">\n");
      out.write("\t\t\t\t\t\t<button class=\"nav-link active\" type=\"button\" role=\"tab\"\n");
      out.write("\t\t\t\t\t\t\tdata-bs-toggle=\"tab\">Active</button>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\" id=\"approvedTab\">\n");
      out.write("\t\t\t\t\t\t<button class=\"nav-link\" type=\"button\" role=\"tab\"\n");
      out.write("\t\t\t\t\t\t\tdata-bs-toggle=\"tab\">Approved</button>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\" id=\"deniedTab\">\n");
      out.write("\t\t\t\t\t\t<button class=\"nav-link\" type=\"button\" role=\"tab\"\n");
      out.write("\t\t\t\t\t\t\tdata-bs-toggle=\"tab\">Denied</button>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<div id=\"display\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- Request Modal -->\n");
      out.write("\t\t<div class=\"modal fade\" id=\"requestModal\" tabindex=\"-1\"\n");
      out.write("\t\t\taria-labelledby=\"requestModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t<h5 class=\"modal-title\" id=\"requestModalLabel\">Request</h5>\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\"></button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mb-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"rAmount\" class=\"form-label\">Amount</label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"rAmount\" name=\"amount\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mb-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"rFor\" class=\"form-label\">For</label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"rFor\" name=\"for\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary\" id=\"submitRequest\"\n");
      out.write("\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\">Submit</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\n");
      out.write("\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\">Close</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"modal fade\" id=\"updateModal\" tabindex=\"-1\"\n");
      out.write("\t\t\taria-labelledby=\"updateModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t<h5 class=\"modal-title\" id=\"updateModalLabel\">Update</h5>\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\"></button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group mb-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"First Name\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=");
out.print(fName);
      out.write(" class=\"form-control\" id=\"fName\">\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-outline-secondary\" type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"submitFirst\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"bi bi-pencil\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group mb-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Last Name\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=");
out.print(lName);
      out.write(" class=\"form-control\" id=\"lName\">\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-outline-secondary\" type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"submitLast\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"bi bi-pencil\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group mb-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" placeholder=\"email\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=");
out.print(email);
      out.write(" class=\"form-control\" id=\"email\">\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-outline-secondary\" type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"submitEmail\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"bi bi-pencil\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\n");
      out.write("\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\">Close</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</main>\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.6.0.js\"\n");
      out.write("\t\tintegrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/employee.js\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("\t\tintegrity=\"sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf\"\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
